import { FLOW_REVISION, PROMPT_VERSION, type TelemetryEvent } from "./events";

/**
 * Seeded demo dataset for the dashboard's "Reset fixtures" affordance.
 *
 * These are synthetic — built directly as typed events, not run through the
 * live app — so a reviewer sees a populated funnel with real friction
 * (C01/C02/C06) without having to hand-drive the chat four times. Every event
 * is tagged `source: "fixture"` so the dashboard can (and does) tell fixture
 * data apart from anything generated by actually using the app.
 */

let counter = 0;
function id(): string {
  counter += 1;
  return `fixture-evt-${counter}`;
}

function base(overrides: {
  readonly sessionId: string;
  readonly attemptId: string;
  readonly turnId?: string;
  readonly timestamp: string;
  readonly platform?: string;
  readonly problemCategory?: TelemetryEvent["problemCategory"];
}) {
  return {
    eventId: id(),
    timestamp: overrides.timestamp,
    sessionId: overrides.sessionId,
    attemptId: overrides.attemptId,
    turnId: overrides.turnId ?? `${overrides.attemptId}-t0`,
    flowRevision: FLOW_REVISION,
    promptVersion: PROMPT_VERSION,
    platform: overrides.platform,
    problemCategory: overrides.problemCategory ?? "none",
    source: "fixture" as const,
  };
}

function t(minutesAgo: number): string {
  return new Date(Date.now() - minutesAgo * 60_000).toISOString();
}

function digest(length: number, hash: string) {
  return { length, hash };
}

const SESSION_A = "session-fixture-a";
const SESSION_B = "session-fixture-b";
const SESSION_C = "session-fixture-c";
const SESSION_D = "session-fixture-d";

export const FIXTURE_EVENTS: readonly TelemetryEvent[] = [
  // ── Attempt 1 — successful control: pause underperformers, full funnel ──
  {
    ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", turnId: "fixture-attempt-1-t0", timestamp: t(240), platform: "meta" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(42, "a1"),
    hadExistingDraft: false,
    existingNodeCount: 0,
    accountId: "act_100200300",
  },
  {
    ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", turnId: "fixture-attempt-1-t0", timestamp: t(239) }),
    type: "draft_changed",
    changeKind: "start",
    nodeCount: 0,
  },
  {
    ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", turnId: "fixture-attempt-1-t0", timestamp: t(238) }),
    type: "draft_changed",
    changeKind: "add_step",
    nodeCount: 3,
  },
  {
    ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", timestamp: t(237) }),
    type: "attempt_outcome",
    outcome: "drafted",
    durationMs: 6200,
    turnCount: 1,
  },
  { ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", timestamp: t(230) }), type: "preview_viewed", nodeCount: 3 },
  { ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", timestamp: t(225) }), type: "draft_saved", ruleId: "201", nodeCount: 3 },
  { ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", timestamp: t(224) }), type: "automation_activated", ruleId: "201", active: true },
  { ...base({ sessionId: SESSION_A, attemptId: "fixture-attempt-1", timestamp: t(60) }), type: "run_succeeded", ruleId: "201", durationMs: 4100, evidence: "simulated" },

  // ── Attempt 2 — C01 repeated confirmation: TikTok pause, already-selected account ──
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", turnId: "fixture-attempt-2-t0", timestamp: t(180), platform: "tiktok", problemCategory: "repeated_confirmation" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(58, "b1"),
    hadExistingDraft: false,
    existingNodeCount: 0,
    accountId: "tt_700800900",
  },
  { ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", timestamp: t(179) }), type: "draft_changed", changeKind: "start", nodeCount: 0 },
  { ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", timestamp: t(178) }), type: "draft_changed", changeKind: "add_step", nodeCount: 3 },
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", problemCategory: "repeated_confirmation", timestamp: t(177) }),
    type: "attempt_outcome",
    outcome: "drafted",
    durationMs: 5800,
    turnCount: 1,
  },
  // Customer says "build" — the bug: same draft rebuilt, same closing repeated.
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", turnId: "fixture-attempt-2-t1", timestamp: t(176), problemCategory: "repeated_confirmation" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(5, "b2"),
    hadExistingDraft: true,
    existingNodeCount: 3,
    accountId: "tt_700800900",
  },
  { ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", timestamp: t(175) }), type: "draft_changed", changeKind: "start", nodeCount: 0 },
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", problemCategory: "repeated_confirmation", timestamp: t(174) }),
    type: "attempt_outcome",
    outcome: "waiting",
    durationMs: 5100,
    turnCount: 2,
  },
  // Third confirmation-only message, still no save — attempt abandoned.
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", turnId: "fixture-attempt-2-t2", timestamp: t(173), problemCategory: "repeated_confirmation" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(4, "b3"),
    hadExistingDraft: true,
    existingNodeCount: 3,
    accountId: "tt_700800900",
  },
  {
    ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", problemCategory: "repeated_confirmation", timestamp: t(172) }),
    type: "attempt_outcome",
    outcome: "waiting",
    durationMs: 4900,
    turnCount: 3,
  },
  { ...base({ sessionId: SESSION_B, attemptId: "fixture-attempt-2", timestamp: t(170) }), type: "attempt_abandoned", lastOutcome: "waiting", turnCount: 3 },

  // ── Attempt 3 — C02 schedule fidelity: Sheets Mon/Tue/Wed 9am EEST ──
  {
    ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", turnId: "fixture-attempt-3-t0", timestamp: t(120), problemCategory: "schedule_fidelity" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(88, "c1"),
    hadExistingDraft: false,
    existingNodeCount: 0,
  },
  { ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", timestamp: t(119) }), type: "draft_changed", changeKind: "start", nodeCount: 0 },
  { ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", timestamp: t(118) }), type: "draft_changed", changeKind: "add_step", nodeCount: 1 },
  {
    ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", turnId: "fixture-attempt-3-t0", problemCategory: "schedule_fidelity", timestamp: t(117) }),
    type: "question_asked",
    questionDigest: digest(63, "c2"),
    reason: "schedule_fidelity",
  },
  {
    ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", problemCategory: "schedule_fidelity", timestamp: t(116) }),
    type: "attempt_outcome",
    outcome: "blocked",
    durationMs: 5400,
    turnCount: 1,
  },
  { ...base({ sessionId: SESSION_C, attemptId: "fixture-attempt-3", timestamp: t(110) }), type: "attempt_abandoned", lastOutcome: "blocked", turnCount: 1 },

  // ── Attempt 4 — C06 unsupported platform, AFTER the fix: mismatch caught, picker resolved ──
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", turnId: "fixture-attempt-4-t0", timestamp: t(40), platform: "meta", problemCategory: "unsupported_platform" }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(50, "d1"),
    hadExistingDraft: false,
    existingNodeCount: 0,
    accountId: "act_100200300",
  },
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", turnId: "fixture-attempt-4-t0", problemCategory: "unsupported_platform", timestamp: t(39) }),
    type: "question_asked",
    questionDigest: digest(70, "d2"),
    reason: "unsupported_platform",
  },
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", problemCategory: "unsupported_platform", timestamp: t(38) }),
    type: "attempt_outcome",
    outcome: "waiting",
    durationMs: 3200,
    turnCount: 1,
  },
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", turnId: "fixture-attempt-4-t1", timestamp: t(37) }),
    type: "question_answered",
    turnId: "fixture-attempt-4-t0",
    answeredAfterMs: 45000,
  },
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", turnId: "fixture-attempt-4-t1", platform: "pinterest", timestamp: t(36) }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(28, "d3"),
    hadExistingDraft: false,
    existingNodeCount: 0,
    accountId: "pin_500600700",
  },
  { ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", timestamp: t(35) }), type: "draft_changed", changeKind: "start", nodeCount: 0 },
  { ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", timestamp: t(34) }), type: "draft_changed", changeKind: "add_step", nodeCount: 3 },
  {
    ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", platform: "pinterest", timestamp: t(33) }),
    type: "attempt_outcome",
    outcome: "drafted",
    durationMs: 5600,
    turnCount: 2,
  },
  { ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", timestamp: t(30) }), type: "preview_viewed", nodeCount: 3 },
  { ...base({ sessionId: SESSION_D, attemptId: "fixture-attempt-4", timestamp: t(28) }), type: "draft_saved", ruleId: "202", nodeCount: 3 },

  // ── Attempt 5 — C06 BEFORE the fix (baseline, for comparison): silent Meta build ──
  {
    ...base({ sessionId: "session-fixture-e", attemptId: "fixture-attempt-5", turnId: "fixture-attempt-5-t0", platform: "meta", problemCategory: "unsupported_platform", timestamp: t(400) }),
    type: "attempt_started",
    mode: "build",
    promptDigest: digest(50, "e1"),
    hadExistingDraft: false,
    existingNodeCount: 0,
    accountId: "act_100200300",
  },
  { ...base({ sessionId: "session-fixture-e", attemptId: "fixture-attempt-5", timestamp: t(399) }), type: "draft_changed", changeKind: "start", nodeCount: 0 },
  { ...base({ sessionId: "session-fixture-e", attemptId: "fixture-attempt-5", timestamp: t(398) }), type: "draft_changed", changeKind: "add_step", nodeCount: 2 },
  {
    ...base({ sessionId: "session-fixture-e", attemptId: "fixture-attempt-5", problemCategory: "unsupported_platform", timestamp: t(397) }),
    type: "attempt_outcome",
    outcome: "drafted",
    durationMs: 5000,
    turnCount: 1,
  },
];
